const content = {
  zh: {
    "nav.product": "产品",
    "nav.traction": "增长",
    "nav.useCases": "药企场景",
    "nav.about": "团队",
    "actions.demo": "预约演示",
    "hero.eyebrow": "FRONTIER AI FOR ONCOLOGY DATA OPS",
    "hero.title": "面向药企与医疗机构的 Agent 治理肿瘤专病数据库",
    "hero.subtitle": "从自由文本到结构化数据，再到自动化分析，全链路可审计、可运营、可规模化，打造下一代肿瘤真实世界数据引擎。",
    "hero.primaryCta": "申请试点",
    "hero.secondaryCta": "查看商业进展",
    "hero.stats.accuracy": "关键字段抽取准确率",
    "hero.stats.time": "数据准备周期缩短",
    "hero.stats.cycle": "分析报告交付周期",
    "panel.title": "旗舰产品",
    "panel.name": "OncoAgent Data Fabric",
    "panel.items.0": "多源肿瘤病历文本自动解析与标准化",
    "panel.items.1": "Agent 编排治理、阈值控制与质量审计",
    "panel.items.2": "分钟级自动产出队列分析与疗效洞察",
    "panel.items.3": "证据链可追溯与专家复核闭环",
    "product.eyebrow": "PRODUCT CORE",
    "product.title": "AI 前沿创业公司的企业级产品能力",
    "product.cards.0.title": "文本结构化引擎",
    "product.cards.0.body": "病历、检验、影像、病理等异构文本统一抽取与医学编码。",
    "product.cards.1.title": "Agent 治理层",
    "product.cards.1.body": "多 Agent 协同编排，策略版本化管理与质量阈值自动校验。",
    "product.cards.2.title": "自动分析引擎",
    "product.cards.2.body": "自动生成队列画像、治疗路径、复发风险与运营 KPI 看板。",
    "product.cards.3.title": "合规内建",
    "product.cards.3.body": "端到端权限审计、脱敏策略、私有化部署与合规治理能力。",
    "traction.eyebrow": "INVESTOR SNAPSHOT",
    "traction.title": "为路演场景设计的增长与交付指标",
    "traction.cards.0.title": "生态合作机构",
    "traction.cards.0.body": "覆盖肿瘤中心、区域医疗集团与科研平台。",
    "traction.cards.1.title": "临床文本处理规模",
    "traction.cards.1.body": "持续扩大高价值肿瘤真实世界数据资产。",
    "traction.cards.2.title": "平台可用性",
    "traction.cards.2.body": "稳定支撑试点、生产与多中心协同场景。",
    "workflow.eyebrow": "END-TO-END PIPELINE",
    "workflow.title": "从自由文本到自动分析的四步闭环",
    "workflow.steps.0.title": "数据接入",
    "workflow.steps.0.body": "统一接入 EMR、LIS、PACS 与随访文本。",
    "workflow.steps.1.title": "Agent 抽取",
    "workflow.steps.1.body": "基于肿瘤知识图谱完成实体、事件与时间线抽取。",
    "workflow.steps.2.title": "治理质控",
    "workflow.steps.2.body": "规则引擎自动质控，异常样本进入专家复核流程。",
    "workflow.steps.3.title": "洞察交付",
    "workflow.steps.3.body": "快速输出疾病队列洞察、疗效分层与业务决策指标。",
    "cases.eyebrow": "BIOPHARMA FIRST",
    "cases.title": "药企优先的真实世界数据应用场景",
    "cases.cards.0.title": "药企医学与临床团队",
    "cases.cards.0.body": "用于方案优化、入排标准评估与治疗路径洞察。",
    "cases.cards.1.title": "商业与市场准入团队",
    "cases.cards.1.body": "输出分层人群、治疗行为与区域差异的决策依据。",
    "cases.cards.2.title": "医学研究机构与医院",
    "cases.cards.2.body": "快速构建专病数据库并提升科研协作效率。",
    "about.eyebrow": "TEAM & VISION",
    "about.title": "我们是一家面向全球市场的 AI 前沿创业团队",
    "about.body": "团队融合肿瘤医学、NLP 与数据工程能力，持续构建 Agent 原生的数据治理基础设施，为药企与医疗机构提供可规模复制的智能平台。",
    "about.metrics.0.title": "产品导向",
    "about.metrics.0.body": "以交付价值为核心，持续迭代可落地的行业方案。",
    "about.metrics.1.title": "技术导向",
    "about.metrics.1.body": "坚持 Agent 治理、可解释性与可靠性工程。",
    "about.metrics.2.title": "商业导向",
    "about.metrics.2.body": "面向药企关键场景构建长期复利的数据网络效应。",
    "cta.title": "准备好把肿瘤数据转化为可执行的业务增长引擎",
    "cta.body": "联系我们获取白皮书、POC 方案与面向药企的定制演示。"
  },
  en: {
    "nav.product": "Product",
    "nav.traction": "Traction",
    "nav.useCases": "Biopharma",
    "nav.about": "Team",
    "actions.demo": "Book a Demo",
    "hero.eyebrow": "FRONTIER AI FOR ONCOLOGY DATA OPS",
    "hero.title": "An Agent-Governed Oncology Data Platform for Biopharma and Providers",
    "hero.subtitle": "From free text to structured datasets to automated analysis, we deliver an auditable and scalable engine for oncology real-world intelligence.",
    "hero.primaryCta": "Start Pilot",
    "hero.secondaryCta": "See Traction",
    "hero.stats.accuracy": "Critical-field extraction accuracy",
    "hero.stats.time": "Reduction in data preparation cycle",
    "hero.stats.cycle": "Insight report turnaround",
    "panel.title": "Flagship Product",
    "panel.name": "OncoAgent Data Fabric",
    "panel.items.0": "Automated normalization of multi-source oncology records",
    "panel.items.1": "Agent orchestration governance with policy and QA thresholds",
    "panel.items.2": "Minute-level cohort analytics and treatment insights",
    "panel.items.3": "Traceable evidence chain with expert-in-the-loop review",
    "product.eyebrow": "PRODUCT CORE",
    "product.title": "Enterprise Capability Built by a Frontier AI Startup",
    "product.cards.0.title": "Text-to-Structure Engine",
    "product.cards.0.body": "Unified extraction and medical coding across EMR, lab, imaging and pathology texts.",
    "product.cards.1.title": "Agent Governance Layer",
    "product.cards.1.body": "Multi-agent orchestration with versioned policies and automated quality control.",
    "product.cards.2.title": "Automated Analytics",
    "product.cards.2.body": "Auto-generates cohort profiles, treatment pathways, recurrence risk and KPI dashboards.",
    "product.cards.3.title": "Compliance-by-Design",
    "product.cards.3.body": "End-to-end auditability, de-identification, private deployment and governance controls.",
    "traction.eyebrow": "INVESTOR SNAPSHOT",
    "traction.title": "Traction Metrics Optimized for Pitch Readiness",
    "traction.cards.0.title": "Ecosystem Partnerships",
    "traction.cards.0.body": "Working with cancer centers, healthcare groups and research platforms.",
    "traction.cards.1.title": "Clinical Text Throughput",
    "traction.cards.1.body": "Expanding high-value oncology real-world data assets at scale.",
    "traction.cards.2.title": "Platform Availability",
    "traction.cards.2.body": "Reliable for pilot, production and multi-center collaboration.",
    "workflow.eyebrow": "END-TO-END PIPELINE",
    "workflow.title": "A Four-Step Loop from Free Text to Automated Insight",
    "workflow.steps.0.title": "Data Intake",
    "workflow.steps.0.body": "Unified ingestion across EMR, LIS, PACS and follow-up narratives.",
    "workflow.steps.1.title": "Agent Extraction",
    "workflow.steps.1.body": "Entity, event and timeline extraction with oncology knowledge context.",
    "workflow.steps.2.title": "Governed Validation",
    "workflow.steps.2.body": "Rules-driven quality checks route outliers to expert review workflows.",
    "workflow.steps.3.title": "Insight Delivery",
    "workflow.steps.3.body": "Rapid delivery of cohort insights, efficacy stratification and business KPIs.",
    "cases.eyebrow": "BIOPHARMA FIRST",
    "cases.title": "Biopharma-Centric Real-World Data Applications",
    "cases.cards.0.title": "Medical & Clinical Teams",
    "cases.cards.0.body": "Support protocol optimization, eligibility evaluation and pathway intelligence.",
    "cases.cards.1.title": "Commercial & Market Access",
    "cases.cards.1.body": "Drive segmentation, treatment behavior insights and regional strategy decisions.",
    "cases.cards.2.title": "Research Institutes & Hospitals",
    "cases.cards.2.body": "Accelerate registry construction and cross-team research productivity.",
    "about.eyebrow": "TEAM & VISION",
    "about.title": "A Frontier AI Team Built for Global Healthcare Markets",
    "about.body": "We combine oncology, NLP and data engineering to build an agent-native governance foundation for scalable intelligence delivery.",
    "about.metrics.0.title": "Product-Led",
    "about.metrics.0.body": "Focused on measurable delivery value and repeatable implementation playbooks.",
    "about.metrics.1.title": "Technology-Led",
    "about.metrics.1.body": "Committed to governed agents, explainability and reliability engineering.",
    "about.metrics.2.title": "Business-Led",
    "about.metrics.2.body": "Creating long-term compounding data network effects in biopharma workflows.",
    "cta.title": "Turn Oncology Data into an Executable Growth Engine",
    "cta.body": "Contact us for whitepaper access, POC planning and tailored biopharma demos."
  }
};

const translatableNodes = document.querySelectorAll("[data-i18n]");
const languageButtons = document.querySelectorAll(".lang-btn");

function setLanguage(lang) {
  translatableNodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (content[lang][key]) {
      node.textContent = content[lang][key];
    }
  });

  languageButtons.forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });

  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});
